name: setup_system_ocaml

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#From https://docs.github.com/en/actions/guides/publishing-docker-images
jobs:
  build-system-ocaml:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./systems/ocaml
          push: false
          tags: effecthandlers/effect-handlers:ocaml
      
      - name: Run benchmarks
        run: |
          make bench_ocaml
